name: PineTreePlugin
version: '1.0.0'
main: org.rij.minecraft.PineTree.Bukkit.PTBukkit
api-version: 1.19
author: RedInJector



commands:
  pineTree:
    description: Your description
    usage: /<command> getextensions
    permission: PineTree.commands
    aliases:
      - PT